# General Jekyll Config
pygments: true
url: http://sj-dev.com
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
markdown: kramdown

# Theme customization - please change from the defaults!
theme:
  # Color for top bar, links, etc
  highlight_color: '#3498db'
  damp_highlight_color: '#59A1D1'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    github: sjdev
    hacker_news: sjdev
    twitter: sj_dev
    #linkedin: 

  # "Hi, I'm _______"
  name: Shane Gianelli
  email: sgianelli@sj-dev.com
  tagline: "developer, freelancer, opportunist"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-50443625-1

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: true
